### ISSUE TITLE
Enable the possibility of multiple phases of execution within the same run and add option to ramp up/down run modes

### ISSUE THREAD

**Issue by cristiancreteanu** [adobe/toughday2#7]
#### Context
When running the tests, there is a spike increase from no running tests straight to the number provided by the user, as well as a sudden drop from the user provided load to 0 load at the end. Namely, for the Normal run mode, 'concurrency'(200 by default) threads are created at the beginning of the run and interrupted at the end. As for the Constant Load run mode, 'load'(50 by default) tests are executed every second since the beginning until the end of the execution.

The ramp up/down period is an option to increase/decrease the stress on the server gradually until finally reaching the user defined load. If so desired, ramping up has the advantage of allowing the system to get all the parts working properly at smaller load (e.g. caches, threads) before heavier volume starts exposing bottlenecks in the server, while ramping down gives the system more time to do all the cleaning that needs to be done so that the process will be shutdown gracefully.

#### Desired usage
By default ToughDay run modes will run as they currently do. If the user wants a ramp up/down phase, they will have to specify a 'start' and an 'end'. Moreover, they can specify a 'rate' of addition and an 'interval'(e.g. "1m2s", "1d", "5h3m"; by default: "1s") at which an addition will occur. If the rate is not specified, the 'rate' and 'interval' fields will be configured so that additions will transpire at regular time intervals by dividing the duration (note: in this case, for normal mode, 'interval' might be less than one second). 'rate' will always be positive. If the duration ends before 'end' has been reached or if 'end' is reached before the duration is over, the execution will stop.
- **Normal ramp up** (start < end): 'start' is the number of threads at which the run starts. 'start' workers will be created off the bat. Then, 'rate' workers will be scheduled to be added every 'interval' until the number of workers reaches 'end'.
`java -jar td.jar --host=localhost --duration=20s --runmode type=normal start=10 end=100`
`java -jar td.jar --host=localhost --runmode type type=normal start=0 end=50 rate=10 interval=1m`
- **Normal ramp down** (end < start):  'start' number of threads are created off the bat. Then, 'rate' active workers will be scheduled to be interrupted every 'interval' until there are 'end' left.
`java -jar td.jar --host=localhost --duration=20s --runmode type=normal start=100 end=10`
`java -jar td.jar --host=localhost --runmode type type=normal start=50 end=0 rate=10 interval=1m`
- **Constant Load ramp up** (start < end): 'start' number of test workers will be created in the first second. After 'interval', 'rate' additional workers will be created with each round. The process repeats until the number of workers per round equals 'end'. If the 'rate' is not specified, based on the global duration, the first try will be to make the 'interval' equal to 1. If the 'rate' proves to be too small, 'interval' is incremented to 2 and 'rate' is processed again. The process repeats until 'rate' is >= 1.  
`java -jar td.jar --host=localhost --runmode type=constantload end=50 start=20 rate=10 interval=2s`
`java -jar td.jar --host=localhost --duration=20s --runmode type=constantload start=0 end=30`
- **Constant Load ramp down** (end < start): the initial number of workers in a round is 'start'. Similar to the ramp up, each 'interval', 'rate' workers will be subtracted from the previous round until 'end' workers will be created in the final round.
`java -jar td.jar --host=localhost --runmode type=constantload load=50 end=20 rate=10 interval=2s`
`java -jar td.jar --host=localhost --duration=20s --runmode type=constantload start=40 end=10`

#### Follow up
Since the desire for having a ramp up/down was to give the end point time to warm up/down, it should be possible to do a warm up, keep the load at the highest value and then warm down. By implementing the above-mentioned feature, ToughDay would still have to be run three times to achieve that. Therefore, ToughDay needs to be able to run multiple phases with different configurations within the same run.

### Phases of execution
Currently, the Engine has a test suite, a run mode and a publish mode, thus having only one phase of execution. However, the engine could have several phases running sequentially until the global duration is over.

#### Desired usage
Examples:
`java -jar td.jar --host=localhost --phase --phase --phase`
`java -jar td.jar --host=localhost --phase --add CreateUserTest --phase --add CreatePageTreeTest`
Every phase-related property (tests, run & publish mode; will be detailed several lines below) that comes after '--phase' will be included in that particular phase until another '--phase' is encountered. In the above-mentioned CLI configuration examples, the first run will have three phases, each phase running with the default configuration, which is the same as ToughDay currently runs (default test suite, Normal run mode with concurrency=200, Simple publish mode). The whole run will take, as it does now, by default, one (tough) day, which will be split equally between the three phases (will be detailed shortly). The second run from the example has two phases, each one having only one test, both running with Normal run mode.

Each phase could have its own:
- **Test Suite**
`java -jar td.jar --host=localhost --phase --add CreatePageTreeTest --add CreateUserTest --phase --add CreatePDFTreeTest`
- **Run Mode** 
`java -jar td.jar --host=localhost --phase --runmode type=normal start=0 end=200 rate=10 --phase`
- **Publish mode**
`java -jar td.jar --host=localhost --phase --publishmode type=intervals interval=3s --phase`

Metrics and publishers will remain global. The above-listed properties could also be present at global level. Every test that is added before the first phase will be in the global suite, which will be cloned by every phase, and the phase-local test-related actions (add, config, exclude) will be applied to this suite. As for the run & publish modes, they can be configured globally and inherited by all of the following phases, but the phases themselves can override them.
- `java -jar td.jar --host=localhost --add CreateUserTest --phase --add CreatePageTreeTest --phase --add GetHomepageTest --add CreatePDFTreeTest`
The first phase will have two tests: CreateUserTest and CreatePageTreeTest while the second phase will have three: CreateUserTest, GetHomepageTest and CreatePDFTreeTest.
- `java -jar td.jar --host=localhost --runmode type=constantload start=0 end=50 --phase --runmode type=normal concurrency=100 --phase`
The first phase overrides the global run mode and run Normally with 100 threads, while the second phase will run with the globally configured run mode, namely a ConstantLoad ramp up.
- `java -jar td. jar --host=localhost --publishmode type=intervals interval=3s --phase --phase --publishmode type=simple`
The first phase will run with the globally configured publish mode, while the second phase overrides it.

Aside from these properties, there are also several others that can be configured for a phase:
- **Name**
`java -jar td.jar --host=localhost --phase name=first --phase name=second`
Two phases cannot have the same name.
- **Measurability**
`java -jar td.jar --host=localhost --phase measurable=false --add CreatePageTreeTest --phase measurable=true --add CreateUserTest --runmode type=constantload`
If the results of a certain phase are of no interest to the user, they can specify whether the phase is measurable or not (by default, a phase is measurable). In the example above, the output of the first phase will be suppressed.
- **Using the configuration of another phase**
`java -jar td.jar --host=localhost --phase name=first --phase name=second useconfig=first`
'useconfig' will take all the properties from the specified phase except for its name. Just as with the globally configured properties, it can add/config/exclude tests from the inherited test suite and override the run/publish mode.
`java -jar td.jar --host=localhost --phase name=first --add CreateUserTest --add CreatePageTreeTest --phase name=second useconfig=first --exclude CreatePageTreeTest --add CreatePDFTreeTest`
`java -jar td.jar --host=localhost --phase name=first measurable=false --add CreateUserTest --runmode type=constantload --phase name=second useconfig=first measurable=true --runmode type=normal`
The phase to take the configuration from does not have to be configured before the phase that wants to inherit it.
`java -jar td.jar --host=localhost --phase useconfig=second --phase name=second --runmode type=constantload`
- **Duration**
`java -jar td.jar --host=localhost --phase duration=10s --add CreateUserTest`
`java -jar td.jar --host=localhost --phase --add CreateUserTest --phase --add CreatePageTreeTest`
`java -jar td.jar --host=localhost --duration=2m --phase duration=10s --add CreateUserTest count=10 --phase --add CreatePDFTreeTest`
If the duration of a phase is not specified, then, from the global duration, the specified durations of phases will be subtracted, and the remainder will be shared equally to the phases that have no duration.
Note: If one phase finishes sooner than its duration, then the difference between that duration and the elapsed time in which the phase ran will be shared equally to the remaining phases that, at the beginning, had no duration.

Example of YAML configuration files that fit the new setup:
```yaml
globals:
  duration: 10s
  dryrun: true
  host: localhost
  installsamplecontent: false
runmode:
  type: normal
  concurrency: 200
tests:
- add: CreateUserTest
```

```yaml
globals:
  duration: 30s
  dryrun: true
  host: localhost
  installsamplecontent: false
phases:
- runmode:
    start: 10
    end: 50
    type: constantload
- runmode:
    load: 50
    type: constantload
- runmode:
    start: 50
    end: 0
    type: constantload
publishers:
- add: CSVPublisher
  properties:
    append: false
- add: ConsolePublisher
tests:
- add: CreateUserTest
```

```yaml
globals:
  dryrun: true
  host: localhost
phases:
- tests:
  - add: CreateUserTest
  - add: CreatePageTreeTest
- tests:
  - add: CreatePDFTreeTest
  - add: GetHomepageTest
```

**Comment by andreituicu** [comment]
Thank you for the contribution!
